name: Fedora packages

on:
  push:
  pull_request:

jobs:
  build:
    name: Fedora ${{ matrix.version }} package
    strategy:
      matrix:
        version:
          - 38
          - 39
          - 40

    runs-on: ubuntu-22.04
    container:
      image: fedora:${{ matrix.version}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update packages
        run: yum -y update

      - name: Install packages
        run: yum -y install
          SDL2-devel
          SDL2_mixer-devel
          cmake
          dotnet-sdk-8.0
          fmt-devel
          fontconfig-devel
          freetype-devel
          libjpeg-turbo-devel
          libpng-devel
          qt6-qtbase-devel
          rpm-build
          turbojpeg-devel

      - name: Build Fedora package
        run: |
          echo $(date +"%Y%m%d").$(echo $GITHUB_SHA | cut -b 1-7) > VERSION
          ./gargoyle-buildrpm.sh

      - name: Upload RPM
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: Gargoyle-Fedora-${{ matrix.version }}
          path: ~/rpm_factory/RPMS/x86_64/*.rpm
